version: '3.4'
services:
    react-nginx:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 3000
        ports:
            - 3000:80
        environment:
            - CHOKIDAR_USEPOLLING=true
